/*
 * Generator: emits the products seed migration from the hardcoded seed copy,
 * preserving UUIDs. Run with:  npx vite-node scripts/gen-products-seed.ts
 *
 * The DB is now the single source of truth; the runtime catalog (catalogs.ts)
 * ships empty and hydrates from it. The data literals live in catalogSeed.ts
 * (test + seed fixture), which is what this script reads. New products should
 * normally be added via the Produkte admin UI or a hand-written migration —
 * regenerate this seed only for a full re-import of the fixture copy.
 */
import { writeFileSync } from 'node:fs';
import { SEED_CATALOGS } from '../src/features/offers/data/catalogSeed';

// Preserve source-catalog grouping (SEED_ALL flattens it).
const CATALOGS: Record<string, any[]> = SEED_CATALOGS;

// Data-driven rule migrated out of OfferBuilderPage's hardcoded list.
const ARBEITSZEIT_ID = 'b01429e1-672e-44ae-ae79-1d08c4f7f918';
const WORK_INTENSIVE = new Set([
  'f7a4cb27-d3cf-4e84-ba58-a273da596c06', // Lagerverwaltung
  'ad5d1834-f864-43a1-8be4-2bae0bfeade4', // Anbindung Schankanlage
]);

// Fields that map to typed columns / pricing; everything else → attrs.
const COMMON = new Set(['id', 'code', 'name', 'cat', 't', 'note', 'info', 'price', 'p', 'servicePercent', 'discount']);

const q = (v: unknown): string =>
  v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`;
const j = (o: unknown): string => `'${JSON.stringify(o).replace(/'/g, "''")}'::jsonb`;

const rows: string[] = [];
for (const [catalog, items] of Object.entries(CATALOGS)) {
  items.forEach((it: any, i: number) => {
    const pricing: any = {};
    if (it.price !== undefined) pricing.price = it.price;
    if (it.p !== undefined) pricing.tiers = it.p;
    if (it.servicePercent !== undefined) pricing.servicePercent = it.servicePercent;
    if (it.discount !== undefined) pricing.discount = it.discount;

    const attrs: any = {};
    for (const [k, v] of Object.entries(it)) if (!COMMON.has(k)) attrs[k] = v;

    const autoAdd = WORK_INTENSIVE.has(it.id) ? { productId: ARBEITSZEIT_ID, qty: 10 } : null;

    rows.push(
      `  (${q(it.id)}, ${q(it.code ?? null)}, ${q(it.name)}, ${q(catalog)}, ${q(it.cat ?? null)}, ` +
      `${q(it.t ?? 'o')}, ${q(it.note ?? null)}, ${q(it.info ?? null)}, ${j(pricing)}, ${j(attrs)}, ` +
      `${autoAdd ? j(autoAdd) : 'NULL'}, ${i})`,
    );
  });
}

const sql = `-- Seed: import the hardcoded product catalog into products, preserving
-- UUIDs so existing offers still resolve. GENERATED by
-- scripts/gen-products-seed.ts from src/features/offers/data/catalogs.ts.
-- Non-breaking (Phase 1): the app still reads the hardcoded file.
INSERT INTO products (id, code, name, catalog, category, kind, note, info, pricing, attrs, auto_add, sort) VALUES
${rows.join(',\n')}
ON CONFLICT (id) DO NOTHING;
`;

const outfile = 'supabase/migrations/20260710190000_seed_products.sql';
writeFileSync(outfile, sql);
console.log(`Wrote ${rows.length} products to ${outfile}`);
